wpa-supplicant: Add dependency on openssl
Building of wpa-supplicant failed due to missing dependency on openssl:
crypto_openssl.c:10:30: fatal error: openssl/opensslv.h: No such file or directory

Signed-off-by: Mikhail Durnev <Mikhail_Durnev@mentor.com>